version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: elpsycongroo
    volumes:
      - postgres:/var/lib/postgresql/data
  next:
    build:
      context: ./
      args:
        - NODE_ENV=development
    restart: always
    environment:
      RDS_HOSTNAME: postgres
      RDS_PORT: 5432
      RDS_DB_NAME: postgres
      RDS_USERNAME: root
      RDS_PASSWORD: elpsycongroo
      DB: postgresql://root:prisma@postgres:5432/root
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/next_app/app:delegated
    depends_on:
      - postgres
    healthcheck:
      disable: true
volumes:
  notused:
  postgres:
